# Base
#
# VERSION               0.0.2

FROM       centos
MAINTAINER Puneet Goyal "puneet@codeignition.co"

RUN yum install -y openssh-server

# RUN mkdir /var/run/sshd
# RUN /usr/sbin/sshd

RUN echo "root:root" | chpasswd

EXPOSE 22
