# Base
#
# VERSION               0.0.2

FROM       ubuntu
MAINTAINER Puneet Goyal "pungoyal@gmail.com"

RUN apt-get install -y pwgen openssh-server

RUN echo "root:root" | chpasswd

EXPOSE 22
RUN mkdir /var/run/sshd
RUN /usr/sbin/sshd
